### ISSUE TITLE
Zoids can erase clovers

### ISSUE THREAD

**Issue by timschwab** [AlyaEru/zoirinth#3]
If a zoid runs over a clover, then it covers it with its trail, and you can't see the clover any more

**Comment by AlyaEru** [comment]
Dude zoids eat clovers when they run over them

**Comment by timschwab** [comment]
What! Oh I see. Then, I guess the logic for a level ending is not working haha.

**Comment by AlyaEru** [comment]
bruh I think you need to spend some time playing real zoirinth xD the level doesn't end until you shoot the clovers out of any zoids that ate them

**Comment by timschwab** [comment]
LOOOOL Okay yeah I'll shut up now.... 😆
